-- +goose Up
-- +goose StatementBegin
CREATE TABLE owners (
    owner_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    owner_name NVARCHAR2(255) NOT NULL,
    owner_type NVARCHAR2(255) NOT NULL
);

CREATE TABLE repos (
    repo_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    repo_full_name VARCHAR(255) NOT NULL,
    repo_owner_id NUMBER NOT NULL REFERENCES owners(owner_id) ON DELETE CASCADE,

    PRIMARY KEY (repo_id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE repos;
DROP TABLE owners;
-- +goose StatementEnd
